<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">

  <!-- MSBuild Dependencies -->
  <ItemGroup>
    <PackageReference Include="KSPBuildTools" Version="1.0.0-*" />
    <PackageReference Include="KSPCommunityLib" Version="0.1.1" />
    <PackageReference Include="MinVer" Version="5.0.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <!-- Static Properties -->
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' ">
    <DebugType>portable</DebugType>
  </PropertyGroup>

  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <LangVersion>latest</LangVersion>
    <IsPackable>false</IsPackable>
    <PlatformTarget>x64</PlatformTarget>
    <NoWarn>1701;1702;CS0649;CS1591;</NoWarn>
    <AssemblyCopyright>2025 KSPModdingLibs Contributors</AssemblyCopyright>
    <AssemblyName>Shabby</AssemblyName>
    <KSPBT_ModRoot>$(MSBuildThisFileDirectory)/../GameData/Shabby</KSPBT_ModRoot>
  </PropertyGroup>

  <!-- DLL Dependencies-->
  <ItemGroup>
    <ModReference Include="0Harmony">
      <DLLPath>GameData/000_Harmony/0Harmony.dll</DLLPath>
      <CKANIdentifier>Harmony2</CKANIdentifier>
      <Private>False</Private>
    </ModReference>
  </ItemGroup>

  <!-- Version Files -->
  <ItemGroup>
    <KSPVersionFile Include=".">
      <Destination>$(KSPBT_ModRoot)/Shabby.version</Destination>
      <URL>https://github.com/KSPModdingLibs/Shabby/releases/latest/download/Shabby.version</URL>
      <Download>https://github.com/KSPModdingLibs/Shabby/releases/latest</Download>
    </KSPVersionFile>
  </ItemGroup>
</Project>
