name: Create-Release
# This doesnt actually make the release, it just runs yaclog release and pushes the resulting commit/tag back to the repo

on:
  workflow_dispatch:
    inputs:
      version-string:
        type: string
        description: arguments to pass to yaclog
        required: true

permissions:
  contents: write

jobs:
  yaclog-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Mod Repo
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Python tools
        run: |
          python -m pip install --upgrade pip
          python -m pip install yaclog
          yaclog show

      - name: Run Yaclog
        run: |
          yaclog -fc ${{ inputs.version-string }}

      - name: push
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git push
          git push --tags